export const ROLES = ["OWNER", "ADMIN", "ANALYST", "VIEWER"];

export const EVIDENCE_TYPES = ["VERIFIED", "SUPPORTED", "ESTIMATED", "INFERRED", "ASSUMED", "UNKNOWN"];
/** Evidence types that assert a claim is backed by a cited source. */
export const SOURCED_EVIDENCE_TYPES = ["VERIFIED", "SUPPORTED"];
export const CONFIDENCE = ["HIGH", "MEDIUM", "LOW", "UNKNOWN"];
export const STRENGTH = ["STRONG", "MODERATE", "WEAK", "UNKNOWN"];
export const LEVEL3 = ["LOW", "MEDIUM", "HIGH"];
export const SEVERITY = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];

export const BUSINESS_MODEL_TYPES = [
  "SAAS", "MARKETPLACE", "AGENCY", "PRODUCTIZED_SERVICE", "SUBSCRIPTION", "API", "DATA",
  "LEAD_GENERATION", "AFFILIATE", "DIGITAL_PRODUCT", "COMMUNITY", "MEDIA", "EDUCATION",
  "PROCUREMENT", "DIRECTORY", "AGGREGATOR", "HYBRID", "OTHER",
];

export const SOURCE_TYPES = [
  "COMPANY_SITE", "PRICING_PAGE", "SEARCH_RESULT", "PRODUCT_HUNT", "REDDIT", "APP_STORE", "MARKETPLACE",
  "JOB_BOARD", "NEWS", "REPORT", "BLOG", "SOCIAL", "DIRECTORY", "GOVERNMENT", "OTHER",
];

export const OPPORTUNITY_STATUSES = [
  "DISCOVERED", "RESEARCHING", "ANALYZING", "VALIDATED", "AWAITING_APPROVAL", "APPROVED",
  "EXPERIMENT", "BUILDING", "LAUNCHED", "SCALING", "PAUSED", "REJECTED",
];

export const EXPERIMENT_STATUSES = ["DRAFT", "READY", "RUNNING", "COMPLETED", "CANCELLED"];

export const AGENT_TYPES = ["OPPORTUNITY_SCOUT", "RESEARCH", "COMPETITOR", "BUSINESS_MODEL", "OPPORTUNITY_ANALYST", "BUSINESS_ARCHITECT"];
export const TASK_STATUSES = ["QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", "RETRYING", "WAITING_REVIEW"];
/** Task states from which no further automatic progress happens. */
export const TERMINAL_TASK_STATUSES = ["COMPLETED", "FAILED", "CANCELLED", "WAITING_REVIEW"];
export const TASK_PRIORITIES = ["LOW", "NORMAL", "HIGH", "URGENT"];
export const PRIORITY_RANK = { LOW: 0, NORMAL: 1, HIGH: 2, URGENT: 3 };
export const RUN_STATUSES = ["STARTED", "COMPLETED", "FAILED", "CANCELLED"];
export const DISCOVERY_RUN_STATUSES = ["QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELLED"];

export const AUDIT_ACTIONS = [
  "USER_REGISTERED", "USER_LOGIN", "USER_LOGOUT", "EMAIL_VERIFIED", "PASSWORD_RESET_COMPLETED",
  "OPPORTUNITY_CREATED", "OPPORTUNITY_UPDATED", "OPPORTUNITY_DELETED", "OPPORTUNITY_APPROVED",
  "OPPORTUNITY_REJECTED", "OPPORTUNITY_STATUS_CHANGED",
  "DISCOVERY_STARTED", "DISCOVERY_COMPLETED", "DISCOVERY_CANCELLED",
  "AGENT_TASK_CREATED", "AGENT_TASK_STARTED", "AGENT_TASK_COMPLETED", "AGENT_TASK_FAILED", "AGENT_TASK_RETRIED",
  "AGENT_RUN_STARTED", "AGENT_RUN_COMPLETED", "AGENT_RUN_FAILED",
  "EXPERIMENT_CREATED", "EXPERIMENT_STARTED", "EXPERIMENT_COMPLETED", "EXPERIMENT_CANCELLED",
  "LANDING_PAGE_UPDATED", "LEAD_CAPTURED", "LEAD_UPDATED", "LEAD_DELETED",
  "USER_ROLE_CHANGED", "SYSTEM_CONFIGURATION_CHANGED",
];

export const LEAD_STATUSES = ["NEW", "CONTACTED", "QUALIFIED", "NOT_INTERESTED"];
/** Approved and onward: where a human has said yes (never PAUSED/REJECTED/pre-approval). */
export const APPROVED_STATUSES = ["APPROVED", "EXPERIMENT", "BUILDING", "LAUNCHED", "SCALING"];
/** A public landing page, or a business blueprint, only makes sense from these states. */
export const LANDING_STATUSES = APPROVED_STATUSES;
